version: "3"

services:
  server:
    build: ./server
    expose:
      - ${SERVER_PORT}
    environment:
      APIKEY: ${APIKEY}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/src:/skyscanner-full-stack/server/src
    command: npm start

  client:
    build: ./client
    expose:
      - ${CLIENT_PORT}
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/skyscanner-full-stack/client/src
      - ./client/public:/skyscanner-full-stack/client/public
    links:
      - server
    command: npm start